services:
  db:
    image: mariadb:11.4
    container_name: gestion_tareas_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
      - ./base_de_datos.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gestion_tareas_server
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_healthy

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile.nuxt
    container_name: gestion_tareas_nuxt
    restart: always
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"
    environment:
      NITRO_PORT: ${NUXT_PORT}
    depends_on:
      - server

volumes:
  db_data: